variables:
  GIT_SUBMODULE_STRATEGY: recursive
build image:
  image: docker:20.10.10
  services:
    - name: docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  - docker build -t $CI_REGISTRY_IMAGE .
  - docker push $CI_REGISTRY_IMAGE
