---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cnc-osaca-conf
  labels:
    app: infrastructure
    system: cnc-osaca
    environment: staging
data:
  realtimeapp-cnc-v1.json: |
    {
        "cncConfig": {
            "startupfilePathFivX": "./FiveXKernelRootDir/listen/hochlauf.lis",
            "startupfilePathOsaka": "./OsacaKernelRootDir/listen/hochlauf.lis", 
            "startupfilePath": "./FiveXKernelRootDir/listen/hochlauf.lis", 
            "ncProgramName": "nc_test.nc",
            "numberOfAxes": 6,
            "cycletime": 2000,
            "triggerThreadPriority": 70,
            "txOffset": 0,
            "simulationMode": false
        },
        "connectorConfig": {
            "interface": "macvlan1900isw",
            "interface2": "enp8s0.1900",
            "destinationMacOsacaAlt": "68:ED:A6:03:9E:30",
            "destinationMacOsaka": "00:1B:21:EA:B8:EA",
            "destinationMac": "00:1B:21:EA:B8:EA",
            "destinationMacFiveX": "68:ED:A6:03:9E:24",
            "socketPriority": 6,
            "useTSN": true,
            "destinationIP": "10.58.103.100",
            "destinationPort": 7777,
            "useTCP": false
        },
        "mqttConfig": {
            "Hostname": "localhost", 
            "Port": 30883, 
            "Username": "", 
            "Password": "", 
            "Protocol": "tcp",
            "NcCodeTopic": "ncfile",
            "NcStateTopic": "ncstate",
            "RtAppStateTopic": "state",
            "CncName": "osaca"
        }
    }
  realtimeapp-cnc-v2.json: |
    {
        "cncConfig": {
            "startupfilePathFivX": "./FiveXKernelRootDir/listen/hochlauf.lis",
            "startupfilePathOsaka": "./OsacaKernelRootDir/listen/hochlauf.lis", 
            "startupfilePath": "./FiveXKernelRootDir/listen/hochlauf.lis", 
            "ncProgramName": "nc_test.nc",
            "numberOfAxes": 6,
            "cycletime": 2000,
            "triggerThreadPriority": 70,
            "txOffset": 0,
            "simulationMode": false
        },
        "connectorConfig": {
            "interface": "macvlan1900isg",
            "interface2": "enp8s0",
            "destinationMacOsacaAlt": "00:1B:21:EA:B8:EA",
            "destinationMacOsaka": "68:ED:A6:03:9E:30",
            "destinationMac": "00:1B:21:EA:B8:EA",
            "destinationMacFiveX": "68:ED:A6:03:9E:24",
            "socketPriority": 6,
            "useTSN": true,
            "destinationIP": "10.58.103.100",
            "destinationPort": 7777,
            "useTCP": false
        },
        "mqttConfig": {
            "Hostname": "localhost", 
            "Port": 30883, 
            "Username": "", 
            "Password": "", 
            "Protocol": "tcp",
            "NcCodeTopic": "ncfile",
            "NcStateTopic": "ncstate",
            "RtAppStateTopic": "state",
            "CncName": "osaca"
        }
    }
---
apiVersion: core.isw.de/v1alpha1
kind: RealTimeApp
metadata:
  name: realtimeapp-cnc-osaca
spec:
  podspec: 
      imagePullSecrets:
        - name: gitlab-credentials
      hostNetwork: true
      containers:
      - env:
          - name: APP
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['app']
          - name: NUMBER
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['number']
          - name: PODNAME
            value: "$(APP)-$(NUMBER)"
        name: cnc-osaka
        image: git.isw.uni-stuttgart.de:5000/projekte/forschung/2021_bmwi_sdm4fzi/isw4_konfiguration_und_deployment/cnc:v1
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: true
          runAsUser: 0
          privileged: true
        volumeMounts:
        - name: config-volume
          mountPath: /app/configuration.json
          subPath: realtimeapp-cnc-v1.json
        - name: listen-volume
          mountPath: /app/FiveXKernelRootDir
        - name: event-volume
          mountPath: /events
        resources: {}
      volumes:
      - name: config-volume
        configMap:
          name: cnc-osaca-conf
      - name: listen-volume
        hostPath: 
            path: /home/rbg/git/infrastructure_messe_rt/realtimeapps_configs/FiveXKernelRootDir
            type: Directory
      - name: event-volume
        hostPath:
            path: /home/rbg/git/infrastructure_messe_rt/events
            type: Directory
