---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - core.isw.de
  resources:
  - realtimeapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.isw.de
  resources:
  - realtimeapps/finalizers
  verbs:
  - update
- apiGroups:
  - core.isw.de
  resources:
  - realtimeapps/status
  verbs:
  - get
  - patch
  - update
