apiVersion: v1
kind: Secret
metadata:
  name: gitlab-credentials
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    ewogICAgImF1dGhzIjogewogICAgICAgICJodHRwczovL2dpdC5pc3cudW5pLXN0dXR0Z2FydC5k
    ZTo1MDAwIjogewogICAgICAgICAgICAiYXV0aCI6ICJZV014TWpneU5UWTZhM0poY0RKNE1uaDJj
    MUZ5WmpKTFRtdEJYMlE9IiwKICAgICAgICAgICAgInVzZXJuYW1lIjogImFjMTI4MjU2IiwKICAg
    ICAgICAgICAgInBhc3N3b3JkIjogImtyYXAyeDJ4dnNRcmYyS05rQV9kIiwKICAgICAgICAgICAg
    ImVtYWlsIjogInN0MTE1NjMzQHN0dWQudW5pLXN0dXR0Z2FydC5kZSIKICAgICAgICB9CiAgICB9
    Cn0K
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-credentials
  namespace: update-operator-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    ewogICAgImF1dGhzIjogewogICAgICAgICJodHRwczovL2dpdC5pc3cudW5pLXN0dXR0Z2FydC5k
    ZTo1MDAwIjogewogICAgICAgICAgICAiYXV0aCI6ICJZV014TWpneU5UWTZhM0poY0RKNE1uaDJj
    MUZ5WmpKTFRtdEJYMlE9IiwKICAgICAgICAgICAgInVzZXJuYW1lIjogImFjMTI4MjU2IiwKICAg
    ICAgICAgICAgInBhc3N3b3JkIjogImtyYXAyeDJ4dnNRcmYyS05rQV9kIiwKICAgICAgICAgICAg
    ImVtYWlsIjogInN0MTE1NjMzQHN0dWQudW5pLXN0dXR0Z2FydC5kZSIKICAgICAgICB9CiAgICB9
    Cn0K
---